dist: bionic
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - vendor
# env:
#   DOCKER_COMPOSE_VERSION: 1.4.2
sudo: required
services:
  - mysql
language: php
php:
  - '7.4'
before_script:
  - COMPOSER_MEMORY_LIMIT=-1
  - composer update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbtest;'
  - mysql -e 'SHOW DATABASES;'
  - cp -R ./vendor/laravel/laravel/* .
  - cp .env.example .env
  - cp -R ./.travis/database.php ./config/database.php
  - pwd
  - php artisan migrate
#  - composer dump-autoload --no-scripts
#  - sed -i 's|name="DB_HOST" value="dbtest"|name="DB_HOST" value="127.0.0.1"|g' phpunit.xml
#  - sed -i 's|name="DB_DATABASE" value="dbtest"|name="DB_DATABASE" value="dbtest"|g' phpunit.xml
#  - sed -i 's|name="DB_USERNAME" value="dbuser"|name="DB_USERNAME" value="travis"|g' phpunit.xml
#  - sed -i 's|name="DB_PASSWORD" value="user123"|name="DB_PASSWORD" value=""|g' phpunit.xml
#  - sed -i 's|name="DB_CONNECTION" value="dbtest"|name="DB_CONNECTION" value="mysql"|g' phpunit.xml
#  - cat phpunit.xml
#  - cat .env

script:
  - vendor/bin/phpunit --configuration phpunit.xml
